### ISSUE TITLE
标注坐标超出图片实际大小

### ISSUE THREAD

**Issue by SherlockHolmes221** [chen-judge/RGBTCrowdCounting#10]
为什么会出现标注坐标超出图片实际大小的情况呢，还有就是感觉一部分漏标了
谢谢

**Comment by chen-judge** [comment]
你是不是在RGB上进行了GT的可视化？RGB-T是一对图像，RGB在很多场景下是不可见的，而热感成像效果更稳定，所以我们的数据是在热感成像上进行标注的。同时由于设备原因，两个模态的图像不是严格对齐的。

**Comment by SherlockHolmes221** [comment]
明白了，谢谢
