### ISSUE TITLE
从RGB图像上看标注误差特别大 这样不会影响计数效果吗

### ISSUE THREAD

**Issue by ZZZ429** [chen-judge/RGBTCrowdCounting#11]
![image](https://github.com/chen-judge/RGBTCrowdCounting/assets/115870352/bba85a0b-0e55-46a3-a761-a94b2199062e)
![1386_with_points](https://github.com/chen-judge/RGBTCrowdCounting/assets/115870352/64c1f6ee-6cae-49f2-9ca6-9a8527f04911)
![1276_with_points](https://github.com/chen-judge/RGBTCrowdCounting/assets/115870352/a5a69768-bb99-4887-aaf6-87510712670d)
![1387_with_points](https://github.com/chen-judge/RGBTCrowdCounting/assets/115870352/73d41f8a-eee7-4b1a-9780-a0017f51752a)
![1392_with_points](https://github.com/chen-judge/RGBTCrowdCounting/assets/115870352/762a6e07-7f7a-493d-9a39-9107031515a2)

**Comment by chen-judge** [comment]
我们主要在热成像模态进行标注，不受光线影响。请参考这个issue：[https://github.com/chen-judge/RGBTCrowdCounting/issues/5#issuecomment-1013609846](https://github.com/chen-judge/RGBTCrowdCounting/issues/5#issuecomment-1013609846)
