### ISSUE TITLE
可视化密度图

### ISSUE THREAD

**Issue by SDarknessZX** [chen-judge/RGBTCrowdCounting#6]
您好！！想问您要一下单个图像的密度图预测可视化的代码，能提供一下嘛！感激不尽！！

**Comment by chen-judge** [comment]
这个加几行代码，把输出的density map转化为numpy再保存即可

**Comment by SDarknessZX** [comment]
> 

您好！我增加了代码，但是我发现您的这个BL模型的输出是分辨率80*60的，很小，您是直接通过双线性插值放大吗？还是怎么操作，还有这个输出是一个黑白颜色的，怎么变成彩色的呢？谢谢哥！
